### PR TITLE
Create Part 2 - Views.html

### PR DESCRIPTION
**Pull request by uozcan12**

### CODE REVIEW

**Comment by hehenischal** [comment]
Please Look at the contributions guidelines. 
For your case, you will need to:
1) Create a folder called 'Views'
2) Create `main.html` inside 'Views' folder
3) put your actual content inside `main.html` . if you need to create multiple pages for a single tutorial topic, you can create a main.html along with other html files with names that resemble the content inside html

Lastly, You have more chance of being accepted if you are writing full tutorials that leads to a working project by the end of tutorial.
You PR isnt accepted as of now

**Comment by uozcan12** [comment]
I fixed the code. Than you for your responses

**Review by hehenischal — APPROVED** [review]
LGTM

**Comment by hehenischal** [comment]
you may now add your name to contributors list

**Comment by uozcan12** [comment]
Ok. I will add my name to the contributors list.

**Pull request merged**
